keys:
  - &elxreno age1frn6df3pw3ks05vzc6q5fmfxzwcen44sq4c7xj86hwymfsg3qadq7mxf0d
  - &timeweb age16yqw7uj20hyrefxjdxlkcrf95tllx7f8qk70j69x0s74jnkcfqzsv7j56t
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - age:
      - *elxreno
  - path_regex: secrets/server.yaml$
    key_groups:
    - age:
      - *elxreno
      - *timeweb
