keys:
  - &elxreno age1frn6df3pw3ks05vzc6q5fmfxzwcen44sq4c7xj86hwymfsg3qadq7mxf0d
  - &infinity age12ynl5qz5wf7g5805ptwh04ttzh507w3hmqrgx6de9wes696xgdjqhun3ad
  - &destroyer age1x2ekqe0r6f9fys9fvcgmwq3dlr240gkhadq7syr4hyw4tg5z2scqun8cgl
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - age:
      - *elxreno
      - *infinity
  - path_regex: secrets/server.yaml$
    key_groups:
    - age:
      - *elxreno
      - *destroyer
