keys:
  - &elxreno age1frn6df3pw3ks05vzc6q5fmfxzwcen44sq4c7xj86hwymfsg3qadq7mxf0d
  - &infinity age12ynl5qz5wf7g5805ptwh04ttzh507w3hmqrgx6de9wes696xgdjqhun3ad
  - &timeweb age1r88audjcxj2g68q4v4jc4w0r7p0k3dwzls005luv77pr7zmyxf9sda5dj8
  - &hcloud age1nteja7s64p37q9a5t053f03vphkv4dwevnuqmmakxsw6ac98w9ksjjxtcc
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - age:
      - *elxreno
      - *infinity
  - path_regex: secrets/server.yaml$
    key_groups:
    - age:
      - *elxreno
      - *timeweb
      - *hcloud
