# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [
    "console=ttyS0"
    "console=tty1"
    "nvme.shutdown_timeout=10"
    "libiscsi.debug_libiscsi_eh=1"
  ];
  boot.kernelModules = [ "bochs_drm" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd:1" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/sda1";
      fsType = "vfat";
    };

  fileSystems."/home" =
    {
      device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd:1" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd:1" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/sda2";
      fsType = "btrfs";
      options = [ "subvol=var" "compress-force=zstd:1" ];
    };

  swapDevices = [ ];

}
