{
 "title": "DNSCrypt-Proxy2",
 "tags": [ "dnscrypt-proxy2" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dnscrypt_proxy_uptime_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total queries served",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscrypt_proxy_queries_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total queries by server",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscrypt_proxy_server_queries_total{instance=\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server average response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscrypt_proxy_server_response_time_average_ms{instance=\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dnscrypt_proxy_queries_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Cache hitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dnscrypt_proxy_cache_hit_ratio{instance=\"$instance\", instance=\"$instance\"} * 100",
     "legendFormat": "Hitrate"
    }
   ]
  },
  {
   "title": "Query rate by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dnscrypt_proxy_query_type_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Query rate per upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dnscrypt_proxy_server_queries_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}