# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/17f9713d-f428-41fb-b5f1-2ba2c1f4e511";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd:1" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/17f9713d-f428-41fb-b5f1-2ba2c1f4e511";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd:1" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/17f9713d-f428-41fb-b5f1-2ba2c1f4e511";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd:1" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/22A6-7B80";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0fe19a2a-3477-42aa-a137-1669fef0ff31"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}