# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "ums_realtek" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  #   fileSystems."/" =
  #     { device = "/dev/disk/by-uuid/39d0c00d-05e6-4e0b-9bd9-9ee9f45afd90";
  #       fsType = "btrfs";
  #       options = [ "subvol=root" "" ];
  #     };

  fileSystems."/" = {
    device = "none";
    options = [ "defaults" "size=4G" "mode=755" ];
    fsType = "tmpfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/efc94559-d846-4928-8fdd-4dbf061521e7";
    fsType = "ext4";
  };

  fileSystems."/btrfs-root" = {
    device = "/dev/disk/by-uuid/39d0c00d-05e6-4e0b-9bd9-9ee9f45afd90";
    fsType = "btrfs";
    options = [ "subvolid=0" "compress-force=zstd:1" "discard=async" "space_cache=v2" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/39d0c00d-05e6-4e0b-9bd9-9ee9f45afd90";
    fsType = "btrfs";
    options = [ "subvol=home" "compress-force=zstd:1" "discard=async" "space_cache=v2" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/39d0c00d-05e6-4e0b-9bd9-9ee9f45afd90";
    fsType = "btrfs";
    options = [ "subvol=persist" "compress-force=zstd:1" "discard=async" "space_cache=v2" ];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/39d0c00d-05e6-4e0b-9bd9-9ee9f45afd90";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress-force=zstd:1" "discard=async" "space_cache=v2" ];
  };

  swapDevices = [ ];

}
