name: Build NixOS

on:
  push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        run: |
          echo "Before cleaning:"
          df -h
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/dotnet
          echo "After cleaning:"
          df -h

      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Install Cachix
        uses: cachix/cachix-action@v10
        with:
          name: elxreno
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build NixOS for INFINITY
        run: nix build -L --no-link .#nixosConfigurations.INFINITY.config.system.build.toplevel