name: Build NixOS

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover_jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-jobs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Generate Jobs
        id: generate-jobs
        run: |
          ci=$(nix eval .#ci --json)
          echo "Collected jobs: $ci"
          echo "matrix=$ci" >> $GITHUB_OUTPUT

  build:
    needs: discover_jobs
    if: ${{ needs.discover_jobs.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.discover_jobs.outputs.matrix) }}
    runs-on: ubuntu-24.04${{ matrix.job.arch == 'aarch64' && '-arm' || '' }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: xc2/free-disk-space@d318b6bfb68decb63d13758b37ef0ead3055f9c8 # perf-3 branch
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: elxreno
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.job.name }} job
        run: nix build -L --no-link .#nixosConfigurations.${{ matrix.job.name }}.config.system.build.toplevel
