name: Build NixOS

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover_jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-jobs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Generate Jobs
        id: generate-jobs
        run: |
          ci=$(nix eval .#ci --json)
          echo "Collected jobs: $ci"
          echo "matrix=$ci" >> $GITHUB_OUTPUT

  build:
    needs: discover_jobs
    if: ${{ needs.discover_jobs.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.discover_jobs.outputs.matrix) }}
    runs-on: ubuntu-24.04${{ matrix.job.arch == 'aarch64' && '-arm' || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          nix-permission-edict: true

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://nix-on-droid.cachix.org https://cache.nixos.org/

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: elxreno
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.job.name }} job
        run: nix build -L --no-link .#hydraJobs.${{ matrix.job.name }} ${{ matrix.job.additionalBuildArgs }}
