name: Build NixOS

on:
  push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: xc2/free-disk-space@d318b6bfb68decb63d13758b37ef0ead3055f9c8 # perf-3 branch
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: elxreno
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build NixOS for INFINITY
        run: nix build -L --no-link .#nixosConfigurations.INFINITY.config.system.build.toplevel
